#pragma once
// VIAL
#define VIAL_KEYBOARD_UID {0xF4, 0xAA, 0xC2, 0xF2, 0x55, 0xB9, 0x6A, 0xAC}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

// Bootmagic
// #define BOOTMAGIC_LITE_ROW 0
// #define BOOTMAGIC_LITE_COLUMN 1
// #define BOOTMAGIC_LITE_ROW_RIGHT 6
// #define BOOTMAGIC_LITE_COLUMN_RIGHT 7
